name: {{cookiecutter.project_import}}_env

channels:
  - conda-forge

dependencies:
  - pip==9.0.1
  - wheel==0.29.0
  - Sphinx==1.5.1
  - cython==0.25.2
  {% if cookiecutter.require_numpy == 'y' -%}
  - numpy==1.11.3
  {%- endif %}
